// Writes the contract ABIs to packages/shared/src/abi.ts (as const, for viem type inference).
// Run after `forge build`: `node export-abi.mjs`
import { readFileSync, writeFileSync } from "node:fs";

const contracts = {
  circleAbi: "out/Circle.sol/Circle.json",
  circleFactoryAbi: "out/CircleFactory.sol/CircleFactory.json",
  forwarderAbi: "out/ERC2771Forwarder.sol/ERC2771Forwarder.json",
};

let ts = "// Generated by packages/contracts/export-abi.mjs — do not edit.\n";
for (const [name, path] of Object.entries(contracts)) {
  const { abi } = JSON.parse(readFileSync(path, "utf8"));
  ts += `\nexport const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n`;
}
writeFileSync("../shared/src/abi.ts", ts);
console.log("wrote ../shared/src/abi.ts");
